# Generated by Django 5.1 on 2024-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='(00)00000-0000', max_length=100),
            preserve_default=False,
        ),
    ]
