# Generated by Django 5.1 on 2024-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='profissao',
            field=models.CharField(default='Desconhecida', max_length=100),
            preserve_default=False,
        ),
    ]
